---
instrument: decimator
parent: instruments/default
board: red-pitaya

cores:
  - redp_adc_v1_0
  - redp_dac_v1_0
  - axi_cfg_register_v1_0
  - axi_sts_register_v1_0

memory:
  - name: config
    offset: '0x60000000'
    range: 4K
  - name: status
    offset: '0x50000000'
    range: 4K
  - name: adc_fifo
    offset: '0x43C10000'
    range: 64K

config_registers:
  - led
  - dac[n_dac]

status_registers:
  - adc[n_adc]

parameters:
  fclk0: 200000000
  adc_clk: 125000000
  adc_width: 14
  dac_width: 14
  n_adc: 2
  n_dac: 2
  cic_differential_delay: 1
  cic_decimation_rate: 256
  cic_n_stages: 6

xdc:
  - boards/red-pitaya/config/ports.xdc
  - boards/red-pitaya/config/clocks.xdc

# Drivers

server:
  includes:
    - instruments/default/server.yml
    - instruments/default/drivers.yml

  drivers:
    - instruments/decimator/decimator.hpp
