---
instrument: laser_controller
parent: default
board: red-pitaya

cores:
  - redp_adc_v1_0
  - redp_dac_v1_0
  - pdm_v1_0
  - pulse_generator_v1_0

memory:
  - name: config
    offset: '0x60000000'
    range: 4K
  - name: status
    offset: '0x50000000'
    range: 4K
    protection: read
  - name: xadc
    offset: '0x43C00000'
    range: 64K

config_registers:
  - led
  - laser_current
  - laser_shutdown
  - laser_reset_overvoltage
  - dac[n_dac]

status_registers:
  - adc[n_adc]

parameters:
  fclk0: 200000000
  dac_width: 14
  adc_width: 14
  pwm_width: 10
  n_pwm: 4
  n_dac: 2
  n_adc: 2

xdc:
  - boards/red-pitaya/config/ports.xdc
  - boards/red-pitaya/config/clocks.xdc
  - instruments/laser_controller/expansion_connector.xdc

server:
  includes:
    - instruments/default/server.yml
    - instruments/default/drivers.yml

  drivers:
    - drivers/xadc/xadc.hpp
    - instruments/laser_controller/laser.hpp
