/// Autogenerated DO NOT EDIT
///
/// (c) Koheron

#include <context_base.hpp>
#include <drivers_manager.hpp>
#include <drivers_table.hpp>

template<class Driver>
Driver& ContextBase::get() const {
    return driver_manager->get<driver_id_of<Driver>>();
}

{%- for driver in drivers -%}
{% for object in driver.objects %}
template {{ driver.objects[0]['type'] }}& ContextBase::get<{{ driver.objects[0]['type'] }}>() const;
{% endfor -%}
{%- endfor -%}
