/// Autogenerated DO NOT EDIT
///
/// (c) Koheron

#ifndef __DRIVERS_JSON_HPP__
#define __DRIVERS_JSON_HPP__

#include "server/executor/drivers_json.hpp"
#include <interface_drivers.hpp>

namespace koheron {

inline auto build_drivers_json() {
    return build_drivers_json<
        {%- for d in drivers -%}
        {{ d.name }}Adapter{{ ", " if not loop.last }}
        {%- endfor -%}
    >();
}

} // namespace koheron

#endif // __DRIVERS_JSON_HPP__
