/// Autogenerated DO NOT EDIT
///
/// (c) Koheron

#ifndef __DRIVERS_TABLE_HPP__
#define __DRIVERS_TABLE_HPP__

#include <drivers_utils.hpp>

class NoDriver;
class Server;
{% for driver in drivers %}
class {{ driver.objects[0]["type"] }};
{% endfor -%}

using driver_table = koheron::drivers_table<
{%- for driver in drivers -%}
{{ driver.objects[0]["type"] }}{{ ", " if not loop.last }}
{%- endfor -%}
>;

#endif // __DRIVERS_TABLE_HPP__
