/// {{ driver.class_name|lower }}.hpp
///
/// Autogenerated DO NOT EDIT
///
/// (c) Koheron

#ifndef __{{ driver.class_name|upper }}_HPP__
#define __{{ driver.class_name|upper }}_HPP__

#include <memory>
#include <mutex>

{% for include in driver.includes -%}
#include "{{ include }}"
{% endfor -%}

#include "server/core/driver_adapter.hpp"

namespace koheron {

{# ---------- helpers ---------- #}
{# Build the full PMF expression (with static_cast when needed) #}
{%- macro full_arg_type(a) -%}
{{ 'const ' if a.get('is_const') }}{{ a['type'] }}{{ '&' if a.get('by_reference') }}
{%- endmacro -%}
{%- macro arg_type_list(args) -%}
{%- for a in args -%}
{{ full_arg_type(a) }}{{ ", " if not loop.last }}
{%- endfor -%}
{%- endmacro -%}

using {{ driver.name }}_Adapter = DriverAdapter<
        {{ driver.id }},
        {{ driver.name }},
{% set SEP = joiner(',\n') -%}
{%- for op in driver.operations -%}
{{ SEP() }}        OpDesc<
        {%- if op.needs_cast -%}
            static_cast<{{ op.ret_expr }} ({{ driver.name }}::*)({{ arg_type_list(op.get('arguments', [])) }})>
            (&{{ driver.name }}::{{ op['name'] }})
        {%- else -%}
            &{{ driver.name }}::{{ op['name'] }}
        {%- endif -%}
        , {{ op['id'] }}>
{%- endfor %}
>;

template<>
class Driver<{{ driver.id }}> : public {{ driver.name }}_Adapter {
  public:
    using {{ driver.name }}_Adapter::{{ driver.name }}_Adapter; // inherit constructors
};

} // namespace koheron

#endif //__{{ driver.class_name|upper }}_HPP__
