/// {{ driver.class_name|lower }}.cpp
///
/// Autogenerated DO NOT EDIT
///
/// (c) Koheron

#include "./{{ driver.interface_name }}.hpp"

#include "server/core/driver_op_helpers.hpp"

namespace koheron {

Driver<{{ driver.id }}>::
Driver({{ driver.objects[0]["type"] }}& {{ driver.objects[0]["name"] }}_)
: DriverAbstract({{ driver.id }})
, {{ driver.objects[0]["name"] }}({{ driver.objects[0]["name"] }}_)
{}

{% for operation in driver.operations -%}
/////////////////////////////////////
// {{ operation['name'] }}

template<>
int Driver<{{ driver.id }}>::
        execute_operation<Driver<{{ driver.id }}>::{{ operation['tag'] }}>(Command& cmd)
{
    using C = {{ driver.objects[0]["type"] }};
    {%- if operation.needs_cast %}
    using Ret = {{ operation.ret_expr }};
    using PMF = Ret (C::*)({{ operation.arg_types_str }});
    return op_invoke<{{ driver.id }}, {{ operation['id'] }}>(
        {{ driver.objects[0]["name"] }},
        static_cast<PMF>(&C::{{ operation['name'] }}),
        cmd
    );
    {%- else %}
    return op_invoke<{{ driver.id }}, {{ operation['id'] }}>(
        {{ driver.objects[0]["name"] }},
        &C::{{ operation['name'] }},
        cmd
    );
    {%- endif %}
}

{% endfor %}

int Driver<{{ driver.id }}>::execute(Command& cmd) {
    std::lock_guard lock(mutex);

    switch(cmd.operation) {
{% for operation in driver.operations -%}
      case {{ operation['tag'] }}: {
        return execute_operation<{{ operation['tag'] }}>(cmd);
      }
{% endfor %}
      case {{ driver.tag | lower }}_op_num:
      default:
          return -1;
    }
}

} // namespace koheron
