/// {{ driver.class_name|lower }}.hpp
///
/// Autogenerated DO NOT EDIT
///
/// (c) Koheron

#ifndef __{{ driver.class_name|upper }}_HPP__
#define __{{ driver.class_name|upper }}_HPP__

{% for include in driver.includes -%}
#include "{{ include }}"
{% endfor -%}

#include "server/core/driver_adapter.hpp"

namespace koheron {

{# ---------- helpers ---------- #}
{# Build the full PMF expression (with static_cast when needed) #}
{%- macro full_arg_type(a) -%}
{{ 'const ' if a.get('is_const') }}{{ a['type'] }}{{ '&' if a.get('by_reference') }}
{%- endmacro -%}
{%- macro arg_type_list(args) -%}
{%- for a in args -%}
{{ full_arg_type(a) }}{{ ", " if not loop.last }}
{%- endfor -%}
{%- endmacro -%}

constexpr int {{ driver.name }}Id = {{ driver.id }};

using {{ driver.name }}Adapter = DriverAdapter<
        {{ driver.name }}Id,
        {{ driver.name }},
{% set SEP = joiner(',\n') -%}
{%- for op in driver.operations -%}
{{ SEP() }}        Op<
        {%- if op.needs_cast -%}
            static_cast<{{ op.ret_expr }} ({{ driver.name }}::*)({{ arg_type_list(op.get('arguments', [])) }})>
            (&{{ driver.name }}::{{ op['name'] }})
        {%- else -%}
            &{{ driver.name }}::{{ op['name'] }}
        {%- endif -%}
        {%- set args = op.get('arguments', []) -%}
        {%- if args|length > 0 -%}
        {%- for a in args -%}, "{{ a['name'] }}"{% endfor -%}
        {%- endif -%}
        >
{%- endfor %}
>;

template<>
class Driver<{{ driver.name }}Id> : public {{ driver.name }}Adapter {
  public:
    using {{ driver.name }}Adapter::{{ driver.name }}Adapter; // inherit constructors
};

} // namespace koheron

#endif //__{{ driver.class_name|upper }}_HPP__
