`timescale 1ns / 1ps

// Complete one/two-channel DDS PM subsystem. Each channel occupies 4 KiB.
// Vendor DDS configurations are generated by package_ip.tcl, never committed.
module awg #(
    parameter integer PHASE_WIDTH = 48,
    parameter integer OUTPUT_WIDTH = 16,
    parameter integer MOD_WIDTH = 24,
    parameter integer LUT_BITS = 14,
    parameter integer PRBS_WIDTH = 31,
    parameter integer ENABLE_SINE = 1,
    parameter integer ENABLE_SQUARE = 1,
    parameter integer ENABLE_PULSE = 1,
    parameter integer ENABLE_TRIANGLE = 1,
    parameter integer ENABLE_UP_RAMP = 1,
    parameter integer ENABLE_DOWN_RAMP = 1,
    parameter integer ENABLE_UNIFORM = 1,
    parameter integer ENABLE_GAUSSIAN = 1,
    parameter integer ENABLE_PRBS = 1,
    parameter integer ENABLE_BPSK = 1,
    parameter integer CHANNELS = 1,
    parameter integer AXI_ADDR_WIDTH = 13
) (
    input wire s_axi_aclk, s_axi_aresetn,
    input wire [AXI_ADDR_WIDTH-1:0] s_axi_awaddr,
    input wire [2:0] s_axi_awprot,
    input wire s_axi_awvalid,
    output wire s_axi_awready,
    input wire [31:0] s_axi_wdata,
    input wire [3:0] s_axi_wstrb,
    input wire s_axi_wvalid,
    output wire s_axi_wready,
    output reg [1:0] s_axi_bresp,
    output reg s_axi_bvalid,
    input wire s_axi_bready,
    input wire [AXI_ADDR_WIDTH-1:0] s_axi_araddr,
    input wire [2:0] s_axi_arprot,
    input wire s_axi_arvalid,
    output wire s_axi_arready,
    output reg [31:0] s_axi_rdata,
    output reg [1:0] s_axi_rresp,
    output reg s_axi_rvalid,
    input wire s_axi_rready,

    input wire sample_clk,
    output wire [OUTPUT_WIDTH-1:0] dac0_data,
    output wire [OUTPUT_WIDTH-1:0] dac1_data
);
    reg aw_pending, w_pending, write_active, aw_sent, w_sent;
    reg [AXI_ADDR_WIDTH-1:0] awaddr;
    reg [2:0] awprot;
    reg [31:0] wdata;
    reg [3:0] wstrb;
    reg read_active, read_channel;
    wire write_channel = awaddr[12];
    wire write_missing = write_channel && CHANNELS == 1;
    wire read_missing = read_channel && CHANNELS == 1;
    wire ar_missing = s_axi_araddr[12] && CHANNELS == 1;
    wire [1:0] child_awready, child_wready, child_bvalid, child_arready, child_rvalid;
    wire [1:0] child_bresp [0:1];
    wire [1:0] child_rresp [0:1];
    wire [31:0] child_rdata [0:1];
    wire [OUTPUT_WIDTH-1:0] dac [0:1];
    assign dac0_data = dac[0];
    assign dac1_data = dac[1];

    // Buffer AW and W independently: AXI-Lite permits either to arrive first.
    // Retain the selected bank until its response is consumed.
    assign s_axi_awready = !aw_pending && !write_active;
    assign s_axi_wready = !w_pending && !write_active;
    always @* begin
        s_axi_bvalid = write_active && (write_missing || child_bvalid[write_channel]);
        s_axi_bresp = write_missing ? 2'b10 : child_bresp[write_channel];
        s_axi_rvalid = read_active && (read_missing || child_rvalid[read_channel]);
        s_axi_rresp = read_missing ? 2'b10 : child_rresp[read_channel];
        s_axi_rdata = read_missing ? 32'b0 : child_rdata[read_channel];
    end
    assign s_axi_arready = !read_active && (ar_missing || child_arready[s_axi_araddr[12]]);
    always @(posedge s_axi_aclk) begin
        if (!s_axi_aresetn) begin
            aw_pending <= 0; w_pending <= 0; write_active <= 0;
            aw_sent <= 0; w_sent <= 0;
            awaddr <= 0; awprot <= 0; wdata <= 0; wstrb <= 0;
            read_active <= 0; read_channel <= 0;
        end else begin
            if (s_axi_awvalid && s_axi_awready) begin
                aw_pending <= 1; awaddr <= s_axi_awaddr; awprot <= s_axi_awprot;
            end
            if (s_axi_wvalid && s_axi_wready) begin
                w_pending <= 1; wdata <= s_axi_wdata; wstrb <= s_axi_wstrb;
            end
            if (aw_pending && w_pending && !write_active) begin
                write_active <= 1; aw_sent <= 0; w_sent <= 0;
            end
            if (write_active) begin
                if (child_awready[write_channel]) aw_sent <= 1;
                if (child_wready[write_channel]) w_sent <= 1;
                if (s_axi_bvalid && s_axi_bready) begin
                    write_active <= 0; aw_pending <= 0; w_pending <= 0;
                end
            end
            if (s_axi_arvalid && s_axi_arready) begin
                read_active <= 1; read_channel <= s_axi_araddr[12];
            end
            if (s_axi_rvalid && s_axi_rready) read_active <= 0;
        end
    end

    genvar c;
    generate for (c=0; c<2; c=c+1) begin : g_channels
        if (c < CHANNELS) begin : g_present
            awg_channel #(
                .PHASE_WIDTH(PHASE_WIDTH), .OUTPUT_WIDTH(OUTPUT_WIDTH),
                .MOD_WIDTH(MOD_WIDTH), .LUT_BITS(LUT_BITS), .PRBS_WIDTH(PRBS_WIDTH),
                .ENABLE_SINE(ENABLE_SINE), .ENABLE_SQUARE(ENABLE_SQUARE),
                .ENABLE_PULSE(ENABLE_PULSE), .ENABLE_TRIANGLE(ENABLE_TRIANGLE),
                .ENABLE_UP_RAMP(ENABLE_UP_RAMP), .ENABLE_DOWN_RAMP(ENABLE_DOWN_RAMP),
                .ENABLE_UNIFORM(ENABLE_UNIFORM), .ENABLE_GAUSSIAN(ENABLE_GAUSSIAN),
                .ENABLE_PRBS(ENABLE_PRBS), .ENABLE_BPSK(ENABLE_BPSK),
                .CHANNEL_COUNT(CHANNELS)
            ) channel (
                .s_axi_aclk(s_axi_aclk), .s_axi_aresetn(s_axi_aresetn),
                .s_axi_awaddr(awaddr[11:0]), .s_axi_awprot(awprot),
                .s_axi_awvalid(write_active && !write_missing && write_channel == c && !aw_sent),
                .s_axi_awready(child_awready[c]), .s_axi_wdata(wdata), .s_axi_wstrb(wstrb),
                .s_axi_wvalid(write_active && !write_missing && write_channel == c && !w_sent),
                .s_axi_wready(child_wready[c]), .s_axi_bresp(child_bresp[c]), .s_axi_bvalid(child_bvalid[c]),
                .s_axi_bready(write_active && write_channel == c && s_axi_bready),
                .s_axi_araddr(s_axi_araddr[11:0]), .s_axi_arprot(s_axi_arprot),
                .s_axi_arvalid(!read_active && s_axi_arvalid && s_axi_araddr[12] == c),
                .s_axi_arready(child_arready[c]), .s_axi_rdata(child_rdata[c]), .s_axi_rresp(child_rresp[c]),
                .s_axi_rvalid(child_rvalid[c]), .s_axi_rready(read_active && read_channel == c && s_axi_rready),
                .sample_clk(sample_clk), .dac_data(dac[c])
            );
        end else begin : g_absent
            assign child_awready[c] = 0;
            assign child_wready[c] = 0;
            assign child_bvalid[c] = 0;
            assign child_arready[c] = 0;
            assign child_rvalid[c] = 0;
            assign child_bresp[c] = 2'b10;
            assign child_rresp[c] = 2'b10;
            assign child_rdata[c] = 0;
            assign dac[c] = 0;
        end
    end endgenerate
endmodule
