---
name: zc706-led-blinker
board: boards/zc706

cores:
  - fpga/cores/axi_ctl_register_v1_0
  - fpga/cores/axi_sts_register_v1_0

memory:
  - name: control
    offset: '0x60000000'
    range: 4K
  - name: status
    offset: '0x50000000'
    range: 4K

control_registers:
  - led

status_registers:
  - forty_two

parameters:
  fclk0: 50000000 # FPGA clock speed in Hz

xdc:
  - ./constraints.xdc

drivers:
  - server/drivers/common.hpp
  - ./led_blinker.hpp

web:
  - ./web/index.html
  - web/koheron.ts
  - web/led-blinker.ts
  - ./web/app.ts
  - web/main.css