---
instrument: neutron_pulse_generator
parent: default
board: red-pitaya

cores:
  - redp_adc_v1_0
  - redp_dac_v1_0
  - axi_cfg_register_v1_0
  - axi_sts_register_v1_0
  - comparator_v1_0
  - latch_v1_0
  - one_clock_pulse_v1_0
  - register_v1_0
  - lfsr32_v1_0
  - delay1_v1_0

memory:
  - name: config
    offset: '0x60000000'
    range: 4K
  - name: status
    offset: '0x50000000'
    range: 4K
  - name: dac
    offset: '0x40000000'
    range: 32K
  - name: adc_fifo
    offset: '0x43C10000'
    range: 64K

config_registers:
  - led
  - arm_softtrig
  - acquisitionlength
  - simulationpulseamp
  - simulationpulsefreq
  - operationmode

status_registers:
  - device_version
  - status
  - state

parameters:
  fclk0: 200000000
  bram_addr_width: 13
  dac_width: 14
  adc_width: 14
  n_adc: 2

xdc:
  - boards/red-pitaya/config/ports.xdc
  - boards/red-pitaya/config/clocks.xdc
  - boards/red-pitaya/config/expansion_connector.xdc

# Drivers

server:
  includes:
    - instruments/default/server.yml
    - instruments/default/drivers.yml

  drivers:
    - instruments/neutron_pulse_generator/neutronpulse.hpp
