---
instrument: adc_dac
parent: instruments/default
board: red-pitaya

cores:
  - fpga/cores/axi_cfg_register_v1_0
  - fpga/cores/axi_sts_register_v1_0
  - fpga/cores/redp_adc_v1_0
  - fpga/cores/redp_dac_v1_0

memory:
  - name: config
    offset: '0x60000000'
    range: 4K
  - name: status
    offset: '0x50000000'
    range: 4K

config_registers:
  - led
  - dac[n_dac]

status_registers:
  - adc[n_adc]

parameters:
  fclk0: 200000000
  dac_width: 14
  adc_width: 14
  n_dac: 2
  n_adc: 2

xdc:
  - boards/red-pitaya/config/ports.xdc
  - boards/red-pitaya/config/clocks.xdc

# Drivers

server:
  includes:
    - instruments/default/server.yml
    - instruments/default/drivers.yml

  drivers:
    - ./adc_dac.hpp
